### PR TITLE
Fixed "warning: assigned but unused variable" in 'rake check:syntax'

### PR DESCRIPTION
**Pull request by mvidner**

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM

**Comment by jreidinger** [comment]
btw rubocop will also find unused variables ;)

**Comment by teclator** [comment]
no changes entry needed?

**Comment by jreidinger** [comment]
@teclator if it goes together with other one, then not

**Comment by teclator** [comment]
@jreidinger so if they go together make sense to be separated PR?

**Comment by teclator** [comment]
in that case LGTM

**Pull request merged**
