### PR TITLE
Make service evaluation lazy

### PR DESCRIPTION
**Pull request by imobachgs**
Implements a alternative (and proper) solution to [bsc#990453](https://bugzilla.suse.com/show_bug.cgi?id=990453) as @mvidner suggested instead of the hack I wrote in https://github.com/yast/yast-dns-server/pull/59 :)

### CODE REVIEW

**Comment by mvidner** [comment]
This looks good, thanks a lot! 
I propose this for .changes:

> Fix an Internal Error 'undefined method DnsSequence' in case bind.rpm is not installed (bsc#990453)

And an explanation in the commit message: 

If we call these in the initialization method of an include file, SystemdService will return nil and ServiceStatus will raise, before the user has had a chance to install the missing package.
```rb
service = SystemdService.find("named")
status_widget = ::UI::ServiceStatus.new(service)
```

**Comment by mvidner** [comment]
Er: The code to install the missing package exists, but if we call...

**Comment by imobachgs** [comment]
Thanks. I've updated the PR (and I also added the suggested explanation to the first commit message).

**Comment by mvidner** [comment]
LGTM, thank you!

**Comment by imobachgs** [comment]
Thanks!

**Pull request merged**
